### ISSUE TITLE
How to prevent client disconnecting on failed subscriptions?

### ISSUE THREAD

**Issue by 1N50MN14** [shamblett/mqtt_client#224]
When a subscription fails mqtt_client automatically triggers a disconnect, I declared `onSubscribeFail` to see if I can override the default behavior but that didn't work. I read through the docs to see if there's a different way to accomplish that, but couldn't find any. Apologies forehand if I missed on it.

My use case is in addition to authenticating connections, I'm validating subscriptions server-side as an additional security layer, with the intention of simply not granting access to the topic rather than disconnecting the client all together, that sends my auto-reconnect logic into an infinite loop..

Many thanks

**Comment by shamblett** [comment]
The client doesn't trigger a disconnect on subscribe fail, either disconnect is being called by your code somewhere or more likely  the broker has found something wrong with the subscription and failed it, replied ,then disconnected the client as for a protocol fail. I my experience subscriptions rarely fail as the client ensures you can't send a malformed one.

OK, to see where the disconnect is coming from I'll need a log from when you subscribe until the client disconnects, please turn off autoreconnect before you do this.

You may also want to check your broker logs, the subscription is failing because the server is sending the value MqttQos.failure(value 128) in the qosGrants of the sub ack payload,  they may tell you why that is.

Another test is to run the same subscription against another broker, e.g test.mosquitto.org, if this works it points to your broker.

**Comment by 1N50MN14** [comment]
Thank you he quick feedback. I have `autoreconnect` disabled, nevertheless you're absolutely right as I see MqttDisconnectionOrigin is `unsolicited`. I'm explicitly sending back error code `4`, changed that to `17` which didn't work either I'll have to dig deeper into the broker itself (`aedes`) .

Thanks again this was very helpful

**Comment by 1N50MN14** [comment]
@shamblett Yup it was on the broker side, fixed and now mqtt_client triggers `onSubscribeFail`. Thanks again.
