### ISSUE TITLE
Listen continuously for updates

### ISSUE THREAD

**Issue by KlausJokisuo** [shamblett/mqtt_client#281]
Hi there,

first of all thanks for the great package!

I'm quite new to using MQTT and I'm not sure if I'm doing this correctly or if there is a  bug.

What I'm trying to accomplish is to connect to the broker and subscribe to a topic and listen to its changes until disconnected.

Below code should subscribe to mqtt.hsl.fi broker and listen for everything but for some reason I get only 1-3 messages and then it stops. 

If I do same with node mqtt package I will receive messages continuously `mqtt subscribe -h mqtt.hsl.fi -l mqtts -p 8883 -v -t "/hfp/v2/journey/#"`

```dart
import 'package:mqtt_client/mqtt_client.dart';
import 'package:mqtt_client/mqtt_server_client.dart';

Future<void> main() async {
  final client = MqttServerClient('mqtt.hsl.fi', '1');
  client.keepAlivePeriod = 60;
  client.onConnected = onConnected;
  client.onDisconnected = onDisconnected;
  client.logging(on: false);

  // let's connect to mqtt broker
  try {
    client.autoReconnect = true;
    await client.connect();
    client.subscribe("/hfp/v2/journey/#", MqttQos.atMostOnce);
    client.updates!.listen((List<MqttReceivedMessage<MqttMessage?>>? c) {
      final recMess = c![0].payload as MqttPublishMessage;
      final pt =
          MqttPublishPayload.bytesToStringAsString(recMess.payload.message!);
      print(
          'EXAMPLE::Change notification:: topic is <${c[0].topic}>, payload is <-- ${pt.length} -->');
      print('');
    });
  } on NoConnectionException catch (e) {
    print(e.toString());
  }
}

void onDisconnected() {
  print('Disconnected');
}

void onConnected() {
  print('Connected');
}
```

Any ideas? 

Thanks.

**Comment by shamblett** [comment]
OK, just looking at your node MQTT package example you are using port 8883, which is the secure MQTT port, your actual code example doesn't set secure working so you are using the default MQTT port which is 1883. To run your code in the VM you need to add an async wait at the end, the listen method does not keep the VM process alive so add this at the end of main -
```
await MqttUtilities.asyncSleep(20); //Or whatever time you want
```
When I run your example as is it receives a few messages then fails with invalid message errors, this is because your broker is an MQTT 3.1.1 broker and you are using the default client version of MQTT 3.1, add this is in your client set up code -
```
client.setProtocolV311();
```

Seems to work better now.

**Comment by KlausJokisuo** [comment]
Huge thanks to you @shamblett Got it all working :)
