### ISSUE TITLE
We have to be able to set Qos in unsubscribe

### ISSUE THREAD

**Issue by MohammedNoureldin** [shamblett/mqtt_client#312]
After days of debugging, I finally found that AWS IOT requires `Qos` to be in the payload of the `unsubscribe` message, otherwise the connection will be disconnected with a `CLIENT_ERROR`.

So in the following:

```
  void unsubscribe(String topic) {
    final unsubscribeMsg = MqttUnsubscribeMessage()
        .withMessageIdentifier(messageIdentifierDispenser.getNextMessageIdentifier())
        .fromTopic(topic);
    connectionHandler!.sendMessage(unsubscribeMsg);
    pendingUnsubscriptions[unsubscribeMsg.variableHeader!.messageIdentifier] = topic;
  }
```

I tried adding `.expectAcknowledgement();` to the unsubscribe message, and the problem was solved. So it will look like this:

```
  void unsubscribe(String topic) {
    final unsubscribeMsg = MqttUnsubscribeMessage()
        .withMessageIdentifier(messageIdentifierDispenser.getNextMessageIdentifier())
        .fromTopic(topic)
        .expectAcknowledgement(); // <<-- NOTICE HERE

    connectionHandler!.sendMessage(unsubscribeMsg);
    pendingUnsubscriptions[unsubscribeMsg.variableHeader!.messageIdentifier] = topic;
  }
```

Could you please add an optional parameter to the unsubscribe method to enable adding the Qos to the payload?

**Comment by shamblett** [comment]
This sounds reasonable, I'll update the client to do this, expect a new version in the next couple of days.

**Comment by shamblett** [comment]
Update added, optional parameter expectAcknowledge added to the unsubscribe method, package re published at version 9.6.0

**Comment by MohammedNoureldin** [comment]
Thank you for the update! Just one notice, shouldn't we be able to specify the `Qos` (0, 1 or 2) instead of only true or false?

**Comment by shamblett** [comment]
I don't think so in this case, although MQTT specifies 3 Qos levels some brokers like AWS and Google's IOT Core only use 2, Qos 0 and Qos 1, in this case if you leave the setting false you get Qos 0, if you set it you get Qos 1 which is what AWS expects and the MQTT 3.1 spec needs, note if you set the client MQTT version to 3.1.1 rather than 3.1 then this is forced in the message, however being able to specify this is more explanatory. Lets see how this goes, if other users ask for Qos specification I'll have another look.

**Comment by MohammedNoureldin** [comment]
Makes sense, thanks a lot!
