### ISSUE TITLE
Image Stream Delay

### ISSUE THREAD

**Issue by Fethi1** [shamblett/mqtt_client#361]
i have a python publisher running on my pc feeding webcam stream through topic to the mosquitto broker running on LAN, when the image stream is received it is late for about 4 - 10 seconds for some reason, I made a python subscriber running locally and the results were perfect (i know it has better bandwidth) but I don't know I set QoS level to 0, any ideas? btw the image is encode to and from base64

**Comment by shamblett** [comment]
Not sure what you mean, the client runs in a Dart VM/Flutter runtime environment, you don't say what 'locally' means, you also don't say what 'better bandwidth' means in relation to the client, if you are saying that Python code executes faster than Dart on your environment then this may well be the case, you could ask the Google guys about this I guess.

If you have any evidence that the slowness you report is caused by the client code then I'll have  a look at it.

**Comment by Fethi1** [comment]
well sorry for not giving many details, I mean by 'locally' that the broker is running on LAN, and for 'bandwidth' i meant faster wifi latency, well that's exactly what affected the performance, I tried running the same python subscriber on another pc connected to the same network and it was laggy as well so it has nothing to deal with this package and with Flutter in general, I'll move to using RTSP for video streaming, thanks a lot
