### ISSUE TITLE
mQTT connection failure

### ISSUE THREAD

**Issue by chetan-SMRI** [shamblett/mqtt_client#405]
I have .der and .cer certificate files from my own custom server, when I do try to connect to mQTT it gives error like failed to connect, also when I do check log it shows it tried 3times , but all 3times it displays random ports, not the one that I setup(8883).

I think .der is CA cer file and .cer if private key.

Am I doing something wrong?

**Comment by shamblett** [comment]
I'm not sure what your issue is here, this is normal client/server behaviour, you connect to the server(MQTT broker in your case) on a known port and the server allocates a port for your client to use, this will be different every time you connect(and across all other connected clients). Normally you do not need to know any of this as the platform network stack handles all this for you.

You don't say but if you are seeing TLS Exception or Socket Exception these are not raised by the client, they are raised by the Dart/flutter runtime.

Socket Exception usually means you cannot see your broker, wrong port or some other network issue, TLS Exception means the TLS secure socket negotiation has failed, there can be many reasons for this.

I suggest you check your broker logs to see what it thinks is happening.

**Comment by chetan-SMRI** [comment]
hi
actually , i managed to make it run but now afterwards it again stopped working
![image](https://user-images.githubusercontent.com/84266613/184663790-96ccaeab-b8f0-4a34-b918-396f62b0331b.png)

**Comment by shamblett** [comment]
This is showing that your broker is disconnecting you when it receives the connect message, you need to look at your broker logs to find out why.

**Comment by chetan-SMRI** [comment]
ok,
but this time I have a different kind of issue,

I managed it to be connecting with the server properly, but when I restart app and navigate from splash screen to main and run function, it doesnt connect,
but when I turn off my mobile data and then rerun the function, it just works fine

**Comment by shamblett** [comment]
OK I'm not sure what you are doing exactly but if the package connects successfully in one situation but not another its probably the situation not the package. As I've already said the log you have provided shows that the broker is disconnecting you, you need to look at your broker logs to find out why, there's not much else I can do here.

**Comment by chetan-SMRI** [comment]
Actually, now I managed to run it successfully, but I just need to know how do i use it for multiple screens, 
I mean when I go to different screens, I have to do connect seperately with server for different screen , but it just wastes the time of screen loader.
But I can't figure out any other solution because I need to use listen for each
