### ISSUE TITLE
MQTT on QOS-1 doesn't store payload in case of no internet service

### ISSUE THREAD

**Issue by AbdulMunim21** [shamblett/mqtt_client#508]
To reproduce this bug, keep the Wi-Fi on but disable the internet service
For some reason, it takes time for mqtt to know that it is being disconnected and during that time if we publish a payload, it sends the message instead of storing it in queue and keep on checking it if either message in sent to broker or not
QOS value was 1

**Comment by shamblett** [comment]
The client doesn't do this by design, if you know the internet service is disabled then you should not send messages through the client(there are many means to detect this on whatever platform you are on). The reason the client takes time to register the disconnect is because the Dart/flutter runtime takes some time to detect the disabled internet service before it sends the relevant events to the client which will then disconnect.

In this period the client thinks its still connected and sends the messages as normal. It wouldn't know it had to store it in a queue, the user of course does, you could keep all QOS 1 messages in a send queue and monitor responses from the broker, re sending where needed. There are many ways of doing this varying from user to user and use case to use case, if the client did this no matter what mechanism it adopted it would not suit all users.

**Comment by AbdulMunim21** [comment]
@shamblett Thank you for your response. Will look into this
