### ISSUE TITLE
onDisconnect callback when autoconnect is false or onAutoReconnect callback when autoconnect is set to true not invoking immediately in ios when wifi is turned off

### ISSUE THREAD

**Issue by SannyRai** [shamblett/mqtt_client#542]
disconnect callback is not invoked when wifi is disabled only in ios. ios has to depend on `disconnectOnNoResponsePeriod` for onDisconnect event to trigger

**Comment by shamblett** [comment]
This is because the Dart/flutter runtime on ios doesn't raise a network disconnect event to the client when wifi is disabled, there are many closed issues documenting this.

The client can't respond to events it doesn't receive, this is one reason the disconnect on no ping response functionality was added. Why the Dart/flutter runtime behaves like this on ios is a question for the Google guys.

**Comment by SannyRai** [comment]
Thanks for the info @shamblett
