### ISSUE TITLE
MQTT server unable to connect in background

### ISSUE THREAD

**Issue by tarunmehtag** [shamblett/mqtt_client#555]
In the foreground MQTT connection works fine. But when the phone's light off or the application goes in the background, then MQTT disconnected. Can anyone help me.

**Comment by shamblett** [comment]
The client disconnects because when you go into background you lose your network connection.

You should disconnect the client when you know you are going into background and reconnect it again when you come back into foreground. There are ways you can detect these events on your platform. Please look through the closed issues for more information if you need it.

**Comment by tarunmehtag** [comment]
But I need to stay connected on the background and wanna run some events. 
Can you help me for the same.

**Comment by shamblett** [comment]
You need to look at how foreground/background works for your platform, I'm not sure you can stay connected whilst in the background, either way this is nothing to do with this package. If you are a flutter user I suggest you contact other flutter users for guidance here or as I've said above look through the closed issues.

**Comment by raviatri** [comment]
@tarunmehtag  hi did you able to figured out to handle this gracefully.

**Comment by tarunmehtag** [comment]
@raviatri , it works only on the foreground.
