### ISSUE TITLE
Listen to specific topic.

### ISSUE THREAD

**Issue by uwejan** [shamblett/mqtt_client#69]
This mighty sound silly, but how can i listen as stream for specific topic? just tried the pub example listener block of code, seemed i got it to missed up with my implementation, where have multiple sub with different payloads of json.
Edit: while waiting have tried multiple things without luck, really stuck on this appreciate response.
```
    client.updates.listen((dynamic c) {
      final MqttReceivedMessage mm = MqttReceivedMessage('dummy/topic/third', c[0].payload);
      final String tt = MqttPublishPayload.bytesToStringAsString(mm.payload);
      //tt no luck
      //final String gg  = MqttByteBuffer.readMqttString(mm.payload);
      //gg no luck
    
      print(
          'EXAMPLE::Change notification:: topic is <${c[0].topic}>, payload is <-- $tt -->');
    });
```

**Comment by shamblett** [comment]
Thinking about this I could use this ticket to implement topic filtering as I've been intending for a while but this would take a week or so, if you want an example quickly I can probably provide one in the next few days

**Comment by uwejan** [comment]
Yes. I will wait for this.

**Comment by shamblett** [comment]
OK this where I'm going with this, from my development branch 

/// This class allows specific topics to be listened for. It essentially
/// acts as a bandpass filter for the topics you are interested in if
/// you subscribe to more than one topic or use wildcard topics.
/// Simply construct it, and listen to its message stream rather than
/// that of the client.
class MqttClientTopicFilter {
  /// Construction
  MqttClientTopicFilter(this._topic, this._clientUpdates) {
    _subscriptionTopic = SubscriptionTopic(_topic);
    _clientUpdates.listen(_topicIn);
    _updates =
        StreamController<List<MqttReceivedMessage<MqttMessage>>>.broadcast(
            sync: true);
  }

  String _topic;

  SubscriptionTopic _subscriptionTopic;

  /// The topic on which to filter
  String get topic => _topic;

  Stream<List<MqttReceivedMessage<MqttMessage>>> _clientUpdates;

  StreamController<List<MqttReceivedMessage<MqttMessage>>> _updates;

  /// The stream on which all matching topic updates are published to
  Stream<List<MqttReceivedMessage<MqttMessage>>> get updates => _updates.stream;

  void _topicIn(List<MqttReceivedMessage<MqttMessage>> c) {
    // Pass through if we have a match
    if (_subscriptionTopic.matches(PublicationTopic(c[0].topic))) {
      _updates.add(c);
    }
  }
}

So you just construct one of these and listen on its update interface rather than that of the client, then you get filtered topics.

**Comment by uwejan** [comment]
Great!
#1 how can i link flutter pubspec to dev?
#2 have not tested it yet, but i will right  away, i was running client on my main, and importing it on other screens, with this way of filtering, no need for the client anymore to be imported yes? just subscribe on main, and run the filter on wanted screen, yes?

**Comment by shamblett** [comment]
For 1 you can add this to your pubspec, replacing your existing mqtt_client entry

mqtt_client:
    git:
      url: https://github.com/shamblett/mqtt_client.git
      ref: development

see [here](https://www.dartlang.org/tools/pub/dependencies)

Can't really help with point 2 as I don't use flutter

**Comment by uwejan** [comment]
Pretty sure you do not expect such questions; bare with me please.
is this how am supposed to get the filter to work. Because its not working this way, i get many errors.
`        
String topic 'dummy/topic/third';
var updates
MqttClientTopicFilter clientTopicFilter = MqttClientTopicFilter(topic, updates);
// then i do what i want to do with updates of that specific filter.
`

**Comment by shamblett** [comment]
The 'updates' variable is the one on the client, so do something like this 

String topic 'dummy/topic/third'; 
var client = MqttClient('test.mosquitto.org', ''); //etc etc
MqttClientTopicFilter clientTopicFilter = MqttClientTopicFilter(topic, client);
// Then instead of listening on the client for updates listen on your filter 
clientTopicFilter .updates.listen((List<MqttReceivedMessage<MqttMessage>> c) {.........}

Note this is early code, I've not written any unit tests yet or done any other testing so I'm not saying its working, its just where I am.

**Comment by shamblett** [comment]
Topic filtering now added in version 5.5.0 and re-published
