### ISSUE TITLE
Add Jwt token generation?

### ISSUE THREAD

**Issue by Radagan** [shamblett/mqtt_client#98]
I've been struggling with your Google IoT example. While very nice, the token generation required to make it work in a real application seems very poorly supported by Flutter packages. I noticed the token was hard coded for the example. Considering Google's requirements for iat and exp claims, that approach won't work in practice. 

Is there a standard way of doing this? I'm new to Flutter and Dart. 

Btw, I can generate a valid RSA keypair that Google accepts, it's the token generation that is my block. 

Maybe something like:

client.setPrivateKey(...private key in pem format...);
String token = client.createJwt(...claims...);

**Comment by shamblett** [comment]
OK, the example should really point to this [project](shamblett/iot-home), this shows a fully working client connecting to Googles cloud IOT, I'll update the client to point to this rather than try and explain things here. You should find all you need, I also wrote a medium article on this [here](https://medium.com/@stevehamblett/dart-in-the-iot-world-a-practical-example-601f036212c7) . Have a look at this, if ist not what you want please raise an issue on the iot-home project and I'll have a look at it.

**Comment by Radagan** [comment]
Thank you very much! Your iot-home project is exactly what I needed to see. And thanks for the article link as well. I haven't yet figured out exactly where my jwt creation was off, but yours works beautifully.
